name: Publish Package

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (don't actually publish)"
        required: false
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Publish theme-default package
        run: |
          cd design-system/themes/default
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            bun publish --dry-run
          else
            bun publish
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
