name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check and publish packages
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # Set npm registry and authentication
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

          # Function to check and publish package
          check_and_publish() {
            local package_path="$1"
            local package_name=$(jq -r '.name' "$package_path/package.json")
            local package_version=$(jq -r '.version' "$package_path/package.json")

            echo "Checking package: $package_name@$package_version"

            # Check if version already exists on npm
            if bun pm view "$package_name@$package_version" version >/dev/null 2>&1; then
              echo "Version $package_version for $package_name already exists, skipping..."
              return 0
            fi

            echo "Publishing $package_name@$package_version..."
            cd "$package_path"
            bun publish --access public
            cd - >/dev/null
          }

          # Find all packages with package.json
          find . -name "package.json" -type f | while read -r package_file; do
            package_dir=$(dirname "$package_file")
            check_and_publish "$package_dir"
          done
