name: Publish Package

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run (don't actually publish)"
        required: false
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Publish theme-default package
        run: |
          cd design-system/themes/default
          if [ "${{ github.event.inputs.dry_run }}" = "true" ]; then
            npm publish --dry-run --access public
          else
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
